### PR TITLE
Update/fish update

### LINKED ISSUE #78: The fish collection should update when User update a Fish
After updating a Fish, the page should render updated fish collection without the need to reload

### PR DESCRIPTION
**Pull request by TimNguyen21**
### Issue(s) related to this PR:
* closes #78 
 
 
 ### Type of change made:
* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Styling- no new features

#### If this submission is a new feature:
* [x] Have you added an explanation of what your changes do?
* [x] Have you lint your code locally prior to submission?

### Change Log:
* actions/index.js - Created actions to update and delete fish from Fish store
* containers/EditFish.js - Modified code to use created actions
* containers/FishCaught.js - Modified the code where it doesn't reload the page on update or delete of a Fish
* reducers/currentFish.js - Updates to fish store based on Update or delete
- Removed componentDidUpdate in the FishCaught Component because it was reloading the page when not needed.  Removed the componentDidUpdate and made an action of updating and deleting a fish to the Redux store instead so that there is no need to reload the page or make a Fetch call to update Fish store

### Were there any challenges that arose? If so, how were the addressed?
* Trying to figure out where the re-rendering information is coming from.  After pinpointing the problem, made an adjustment to code to not rely on Fetch call to update Redux, but use Redux itself to update Fish store based on user action to update or delete fish information

### Technical Debt:
* Still need to stop the error message on mobile when using the app.

### Testing:
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] All new and existing tests passed?
* [ ] Have you run linter?

**Test coverage** = 0

### CODE REVIEW

**Comment by rachael-t** [comment]
Thanks, Tim for looking into this! I have some clarifying questions:

1. You mentioned that you need to stop the error message on mobile when using the app - what is that error message you are receiving?
2. Where did you see the re-rendered information occurring? 

Thank you!

**Comment by TimNguyen21** [comment]
> Thanks, Tim for looking into this! I have some clarifying questions:
> 
> 1. You mentioned that you need to stop the error message on mobile when using the app - what is that error message you are receiving?
> 2. Where did you see the re-rendered information occurring? I'm looking at the copy on my local app and browser and am trying to understand where this is occurring.
> 
> Thank you!

No problem.  I can will try to explain the best I can.

1. The error message is the messages of the font problem.  So, basically the console log error we had since the beginning of the project.  I am just referencing that error where it is showing in the Console or when we load the app, the error screen with red text comes on.

2.  In relation to that error page, in the fish caught page always render that error every time we edit, add or delete a Fish.  I track down that re-rendering of that error page from that componentWillUpdate.  This problem only shows up on a mobile device and not a web browser.  On my Android to be specific, it is rendering that error page every time something is changed.  I am not sure about Apple devices.  We can go over the problem tomorrow and I can demo it to show you what is going on.  So for now, let's hold off on the PR merge until I can show the team what is going on and what is changed so that everyone is on the same page. =)

**Comment by TimNguyen21** [comment]
> Thanks, Tim for looking into this! I have some clarifying questions:
> 
> 1. You said you removed the componentWillMount -> did you mean componentDidUpdate on FishCaught.js on lines 32 - 39?
> 2. You mentioned that you need to stop the error message on mobile when using the app - what is that error message you are receiving?
> 
> Thank you!

Yes. Good catch. I meant componentDidUpdate. It's been a long day. hehe

**Comment by rachael-t** [comment]
Tim and I met this morning to go over the changes and clear up any questions I had. It looks like some of the errors that were coming up were specific to Android (what Tim is using) devices and not iOS (what I'm using). We will be making a team decision on which device to focus on this afternoon.

**Pull request merged**
